server:
  port: ":8000"
  timeout:
    read_header: 30
    read: 60
    write: 60

db:
  uri: "mongodb+srv://m001-student:m001-mongodb-basics@sandbox.evatv.mongodb.net/jokes-api?retryWrites=true&w=majority"
  db_name: "jokes-api"
  jokes_collection: "jokes"