version: "3.9"
services:
  jokes-api:
    container_name: jokes-api
    build: ./
    command: ./jokes-api
    ports:
      - "8443"
    networks:
      - main
    
  nginx:
    image: nginx:stable
    restart: always
    container_name: nginx
    depends_on:
      - "jokes-api"

    volumes:
        - ./nginx/service.conf:/etc/nginx/conf.d/default.conf
        - ./nginx/ssl:/etc/ssl

    ports:
        - "8080:80"
        - "8443:443"

    networks:
      - main

networks:
  main:
    

    