version: "3.9"
services:
  jokes-api:
    container_name: jokes-api
    build: ./
    command: ./jokes-api
    networks:
      - backend

  nginx:
    image: nginx:stable
    restart: always
    container_name: nginx
    depends_on:
      - "jokes-api"
    volumes:
      - $PWD/nginx/service:/etc/nginx/conf.d/
      - $PWD/nginx/ssl:/etc/ssl
    ports:
      - "8080:80"
      - "8443:443"
    networks:
      - backend
      
networks:
  backend:
    

    